/**
 * srg4u Authentication REST API
 * 認証認可側API 必要なのはモデル定義のみ
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package models


case class AuthResponse (
  /* アクセストークンが有効か否か */
  active: Option[Boolean],
  client_id: Option[String],
  username: Option[String],
  scope: Option[String],
  sub: Option[String],
  aud: Option[String],
  iss: Option[String],
  exp: Option[String],
  iat: Option[String],
  extension_field: Option[String]
)
